import re
import sys
import os
import datetime
import cxxheaderparser.simple as cxx
import cxxheaderparser.types as cxxtypes

TAB = "    "
NEWLINE = "\n"

DEFAULT_FILENAME = "mock"
HEADER_FILETYPE_SUFFIX = ".h"

DEFAULT_FILENAME_FULL = DEFAULT_FILENAME + HEADER_FILETYPE_SUFFIX

DEFAULT_DESCRIPTION = "GMock class generated by " + os.path.basename(__file__)

ASTERISK_LINE = (
    "******************************************************************************"
)
COPYRIGHT_LINE = "<h2><center>&copy; Copyright (c) {year} Licensed under the MIT License. </center></h2>"

COPYRIGHT_NOTICE = (
    ""
    + "/"
    + ASTERISK_LINE
    + NEWLINE
    + " "
    + ASTERISK_LINE
    + NEWLINE
    + " * @file    {filename}"
    + NEWLINE
    + " *"
    + NEWLINE
    + " * @details {description}"
    + NEWLINE
    + " *"
    + NEWLINE
    + " *"
    + NEWLINE
    + " "
    + ASTERISK_LINE
    + NEWLINE
    + " * @attention"
    + NEWLINE
    + " * "
    + COPYRIGHT_LINE
    + NEWLINE
    + " *"
    + NEWLINE
    + " "
    + ASTERISK_LINE
    + NEWLINE
    + " "
    + ASTERISK_LINE
    + "/"
    + NEWLINE
    + ""
    + NEWLINE
)

IFNDEF_TEXT = "#ifndef"
DEFINE_TEXT = "#define"
ENDIF_TEXT = "#endif"

HEADER_GUARD_TOP = (
    ""
    + IFNDEF_TEXT
    + " _{mock_name}"
    + NEWLINE
    + DEFINE_TEXT
    + " _{mock_name}"
    + NEWLINE
    + ""
    + NEWLINE
)
HEADER_GUARD_BOTTOM = NEWLINE + ENDIF_TEXT + " // _{mock_name}"


class GMockNSHandler:
    def __init__(self):
        self.output = []
        self.mocked_classes = []
        self.inheritance = ""

    def parse(self, scope: cxx.NamespaceScope, inheritance: str = "") -> list:
        if scope.name != "":
            self.inheritance = (
                inheritance + "::" + scope.name + "::"
                if inheritance != ""
                else scope.name + "::"
            )
        # check for children
        if scope.namespaces:
            for namespace in scope.namespaces:
                ns_handler = GMockNSHandler()
                ns_mock = ns_handler.parse(
                    scope.namespaces[namespace], self.inheritance
                )
                if ns_mock:
                    for line in ns_mock:
                        self.output.append(line)

        if scope.name != "":
            self.output.append(f"using namespace {scope.name};\n")
        # check for classes
        if scope.classes:
            for child_class in scope.classes:
                if child_class.class_decl.classkey == "class":
                    class_handler = GMockClassHandler()
                    class_mock = class_handler.parse(
                        child_class, self.inheritance, self.mocked_classes
                    )
                    if class_mock:
                        for line in class_mock:
                            self.output.append(line)

        return self.output


class GMockClassHandler:
    def __init__(self):
        self.output = []
        self.inheritance = ""
        self.bind_function = ""
        self.mock_constructor = []
        self.bind_functions = []
        self.mock_functions = []
        self.name = ""

    def parse(
        self, scope: cxx.ClassScope, inheritance: str = "", local_mocks: list = []
    ) -> list:
        # get name
        self.name = self.get_class_name(scope)

        # check for children
        if scope.classes:
            for child_class in scope.classes:
                class_handler = GMockClassHandler()
                self.output.append(
                    class_handler.parse(
                        child_class,
                        (
                            self.inheritance + "::" + self.name
                            if inheritance != ""
                            else self.name + "::"
                        ),
                    )
                )

        # look for std::function
        for field in scope.fields:
            std_func_handler = GMockStdFuncHandler()
            if std_func_handler.is_std_func(field):
                mockFunc, bindFunc = std_func_handler.parse(
                    field, self.name, inheritance
                )
                if mockFunc:
                    self.mock_functions.append(mockFunc)
                if bindFunc:
                    self.bind_functions.append(bindFunc)

        # parse methods
        for method in scope.methods:
            method_handler = GMockMethodHandler()
            mock, constructors = method_handler.parse(method, self.name, local_mocks)
            if mock:
                self.mock_functions.append(mock)
            if constructors:
                self.mock_constructor.append(constructors)

        # build output only if mocks present
        if self.bind_functions or self.mock_functions or self.mock_constructor:
            self.output.append(
                f"class Mock{self.name} : public {inheritance}{self.name}\n{{"
            )
            if self.bind_functions:
                self.output.append("protected:")
                self.bind_function = f"Bind{self.name}Methods"
                self.output.append(
                    f"\tstatic inline void {self.bind_function}(Mock{self.name}& mock)\n\t{{"
                )
                for func in self.bind_functions:
                    self.output.append(*func)
                self.output.append("\t}\n")
            self.output.append("public:")
            if self.bind_functions or self.mock_constructor:
                self.generate_constructors()
                self.generate_destructors()
            for func in self.mock_functions:
                self.output.append(*func)
            self.output.append("};\n")
            local_mocks.append(self.name)

        return self.output

    def get_class_name(self, scope: cxx.ClassScope):
        return scope.class_decl.typename.format()[6:]

    def generate_constructors(self):
        # NOTE: sub mock construction only supported for mock classes in same header
        # generate constructor to bind or to sub mock
        initStr = f"\tMock{self.name}() : {self.name}("
        subInitStr = "),"
        if not self.mock_constructor:
            self.output.append(f"\tMock{self.name}()\n\t{{")
            if self.bind_function != "":
                self.output.append(f"\t\t{self.bind_function}(*this);")
            self.output.append("\t}")
        else:
            for special_constructor in self.mock_constructor:
                for sub_mock in special_constructor:
                    self.output.append(f"\t{sub_mock[0]} {sub_mock[1]};")
                    initStr = initStr + f"&{sub_mock[1]}, "
                    subInitStr = subInitStr + f" {sub_mock[1]}(),"
                self.output.append(initStr[:-2] + subInitStr[:-1] + f"\n\t{{")
                if self.bind_function != "":
                    self.output.append(f"\t\t{self.bind_function}(*this);")
                self.output.append("\t}")

    def generate_destructors(self):
        # generate destructor
        self.output.append(f"\t~Mock{self.name}()\n\t{{")
        self.output.append("\t}")


class GMockMethodHandler:
    def __init__(self):
        self.return_type = ""
        self.method_name = ""
        self.args = ""
        self.override_key = "override"
        self.mock_output = []
        self.mock_constructor_fields = []

    def parse(self, scope: cxx.Method, classname: str, local_mocks: list = []) -> list:
        # make sure method is public or else cant be mocked
        if self.is_public(scope) and not (scope.constructor or scope.destructor):
            self.return_type = self.get_return_type(scope)
            self.args = self.get_parameters(scope)
            self.method_name = scope.name.format()
            self.mock_output.append(
                f"\tMOCK_METHOD({self.return_type}, {self.method_name}, ({self.args}), ({self.override_key if scope.virtual else ''}));"
            )
        # if the constructor gets class objects passed in, make mock constructor
        # structure
        elif scope.constructor and scope.parameters:
            for arg in scope.parameters:
                arg_mock_format = arg.type.format()[:-1]
                if arg_mock_format in local_mocks:
                    self.mock_constructor_fields.append(
                        [f"Mock{arg_mock_format}", f"mock{arg_mock_format}"]
                    )

        return self.mock_output, self.mock_constructor_fields

    def is_public(self, scope: cxx.Method):
        ret = False
        if hasattr(scope, "access"):
            if scope.access == "public":
                ret = True
        return ret

    def get_return_type(self, scope: cxx.Method):
        try:
            return scope.return_type.typename.format()
        except AttributeError:
            # If return_type is a pointer or reference type cant expand typename directly
            return scope.return_type.format()

    def get_parameters(self, scope: cxx.Method):
        parameters = ""
        for arg in scope.parameters:
            typeStr = arg.type.format()
            argName = "" if arg.name is None else arg.name
            parameters = parameters + typeStr + " " + argName + ", "
        # trim final comma
        return parameters[:-2]


class GMockStdFuncHandler:
    def __init__(self):
        self.return_type = ""
        self.function_name = ""
        self.args = ""
        self.mock_output = []
        self.bind_output = []
        self.std_function_pattern = re.compile(
            r"std::function<([\w:<>,&*]+)\s*\(([\w:<>,\s&*=]+)?\)>"
        )

    def parse(self, scope: cxx.Field, classname: str, inheritance: str = ""):
        if self.is_std_func(scope) and scope.access == "public":
            func_str = scope.type.typename.format()
            class_std_functions = self.std_function_pattern.search(func_str)
            if class_std_functions:
                std_return_type, std_args = class_std_functions.groups()
                if std_args is None:
                    std_args = ""
                std_argc = 0
                clean_args, std_argc = arg_format(std_args, True)
                std_placeholder = (
                    f", std::placeholders::_{std_argc}" if std_argc > 0 else ""
                )
                self.bind_output.append(
                    f"\t\t{inheritance}{classname}::{scope.name} = std::bind(&Mock{classname}::{scope.name}, &mock{std_placeholder});"
                )
                self.mock_output.append(
                    f"\tMOCK_METHOD({std_return_type}, {scope.name}, ({arg_format(std_args)}));"
                )

        return self.mock_output, self.bind_output

    def is_std_func(self, scope: cxx.Field) -> bool:
        try:
            if (
                scope.type.typename.segments[0].name == "std"
                and scope.type.typename.segments[1].name == "function"
            ):
                return True

        except Exception as e:
            return False


def generate_mock_class(filename, output_dir=None):
    """Method to generate a mock for a cpp and c header files

    Known Limitations:
    - nested structures like namespaces inside of namespaces...
    - need to terminate last classes within namespaces as such:
    "
    }; end of class
    } end of namespace
     extra newline
    "
    - std::function calls for now
    Args:
        filename (path): path to header file
        output_dir (path, optional): directory where to write the mock header.
            Defaults to None which prints out generated mock to terminal.
    """
    std_function_pattern = re.compile(r"std::function")

    with open(filename, "r") as file:
        data = file.read()

    output = []
    filename_w_ext = os.path.basename(filename)
    filename_no_ext = os.path.splitext(filename_w_ext)[0]
    # Should always append gtest / gmock headers, and the header referenced for types
    output.append("#include <gtest/gtest.h>")
    output.append("#include <gmock/gmock.h>")
    if std_function_pattern.search(data):
        output.append("#include <functional>")
    output.append('#include "{}"\n'.format(filename_w_ext))

    # parse the header and fill in generated GMock body

    # cxx cannot handle preprocessor directives
    data = preprocessor_trim(data)
    parsed_data = cxx.parse_string(data)
    data_handler = GMockNSHandler()
    mock_content = data_handler.parse(parsed_data.namespace)
    for line in mock_content:
        output.append(line)

    output_str = "\n".join(output)

    if output_dir is not None:
        output_header_name = "mock_" + os.path.basename(filename)
        output_filename = os.path.join(output_dir, output_header_name)
        with open(output_filename, "w") as file:
            write_header(file, output_header_name)
            file.write(output_str)
            write_footer(file, output_header_name)
    else:
        print(output_str)


def arg_format(args, argc=None):
    """format a regex argument string for mocking
    removing default initializers and counting args present

    Args:
        args (str): string of arguments in a header prototype
        argc (bool, optional): flag for returning argc. Defaults to None.

    Returns:
        str: string of arguments with default initializers trimmed
    """
    output_args = ""
    if args is not None:
        default_init_pattern = re.compile(r"\s?=\s?[\w:<>\s&*()]+|\s?void")
        arg_count_pattern = re.compile(r"[\w:<>\s&*()]+")
        output_args = re.sub(default_init_pattern, "", args)
        if output_args is None:
            output_args = ""
        elif argc is not None:
            argc = len(arg_count_pattern.findall(output_args))
            return output_args, argc
    return output_args


def preprocessor_trim(data):
    preprocessor_multiline_pattern = re.compile(r"\\$\n")
    preprocessor_pattern = re.compile(r"#.*\n?")
    output_data = re.sub(preprocessor_multiline_pattern, "", data)
    output_data = re.sub(preprocessor_pattern, "", output_data)
    return output_data


def write_header(file, mock_name=DEFAULT_FILENAME, description=DEFAULT_DESCRIPTION):
    mock_base_name, _ = os.path.splitext(mock_name)
    name_all_caps = str.upper(mock_base_name)
    file.write(
        COPYRIGHT_NOTICE.format(
            filename=mock_name, description=description, year=datetime.date.today().year
        )
    )
    file.write(HEADER_GUARD_TOP.format(mock_name=name_all_caps))


def write_footer(
    file,
    mock_name=DEFAULT_FILENAME,
):
    mock_base_name, _ = os.path.splitext(mock_name)
    name_all_caps = str.upper(mock_base_name)
    file.write(HEADER_GUARD_BOTTOM.format(mock_name=name_all_caps))


if __name__ == "__main__":
    if len(sys.argv) > 2:
        generate_mock_class(sys.argv[1], sys.argv[2])
        print(f"GMock generated for file: {sys.argv[1]}\twritten to: {sys.argv[2]}")
    else:
        generate_mock_class(sys.argv[1])
